trigger:
- master

pool:
      name: Default

steps:

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Application security testing@2024
  inputs:
    
    enableSastScan: true
    CheckmarxService: 'My_SAST'
- task: Checkmarx AST@3
  inputs:
    projectName: 'NodeGoatcopy'
    branchName: '$(Build.SourceBranchName)'
    tenantName: 'ast_abdul_ansari'

