trigger:
- master

pool:
  name: Default

steps:

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Application security testing@2025
  inputs:
    projectName: 'NodeGoatcopy'
    enableProxy: false
    enableSastScan: true
    CheckmarxService: 'CxEndpointlatest'
    enableSastBranching: false
    preset: 'All'
    incScan: false
    generatePDFReport: true
    enableDependencyScan: false