trigger:
- master

pool:
  name: Default
steps:
- task: Application security testing@2025
  inputs:
    projectName: 'NodeGoatcopy'
    enableProxy: false
    enableSastScan: true
    CheckmarxService: 'My_SAST'
    enableSastBranching: false
    preset: 'All'
    fullTeamName: 'CxServer'
    incScan: false
    generatePDFReport: true
    vulnerabilityThreshold: true
    critical: '10'
    high: '10'
    enableDependencyScan: false