trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:


- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Application security testing@2024
  inputs:
    projectName: 'NodeGoatcopy'
    enableProxy: true
    enableSastScan: true
    enableSastBranching: true
    masterBranchProjectName: 'NodeGoatcopy'
    preset: 'All'
    overrideProjectSettings: true
    generatePDFReport: true
    enableDependencyScan: false
  