trigger:
- master

pool:
  name: Default

steps:

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Checkmarx AST@3
  displayName: 'Run Checkmarx AST Scan'
  inputs:
    projectName: 'NodeGoatcopy'
    branchName: '$(Build.SourceBranchName)'
    tenantName: 'ast_abdul_ansari'
    enableProxy: false
    enableSastScan: true
    enableSastBranching: false
    preset: 'High and Medium'
    incScan: false
    generatePDFReport: true

- task: Application security testing@2025
  inputs:
    projectName: 'NodeGoatcopy'
    enableProxy: false
    enableSastScan: true
    enableSastBranching: false
    preset: 'Error handling'
    incScan: false
    generatePDFReport: true
    vulnerabilityThreshold: true
    critical: '10'
    high: '10'
    enableDependencyScan: false